apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-main
spec:
  ingressClassName: nginx
  rules:
  - host: www.502super.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-service1
            port:
              number: 80
              
  - host: www.502super2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-service2
            port:
              number: 80

