apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic2
  template:
    metadata:
      labels:
        app: petclinic2
    spec:
      containers:
      - name: petclinic2
        image: tmddbs1977/spring-petclinic2:latest
        env:
        - name: SERVER_NAME
          value: "WAS-B"
        ports:
        - containerPort: 8080
