apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
spec:
  ingressClassName: petclinic
  rules:
  - http:
      paths:
      - path: /petclinic1
        pathType: Prefix
        backend:
          service:
            name: petclinic-service1
            port:
              number: 80
      - path: /petclinic2
        pathType: Prefix
        backend:
          service:
            name: petclinic-service2
            port:
              number: 80
