apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic1
  template:
    metadata:
      labels:
        app: petclinic1
    spec:
      containers:
      - name: petclinic1
        image: tmddbs1977/spring-petclinic2:latest
        ports:
        - containerPort: 80
